# Generated by Django 6.0.3 on 2026-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'Toyota'), (2, 'Honda'), (3, 'Ford'), (4, 'Chevrolet'), (5, 'Volkswagen'), (6, 'Nissan'), (7, 'Hyundai'), (8, 'Kia'), (9, 'Renault'), (10, 'Peugeot')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'Preto'), (2, 'Branco'), (3, 'Prata'), (4, 'Cinza'), (5, 'Vermelho'), (6, 'Azul'), (7, 'Amarelo')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Flex'), (5, 'Elétrico'), (6, 'Híbrido')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculo/fotos/')),
            ],
        ),
    ]
